version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/cirf-be

permissions:
  - object: /home/ec2-user/cirf-be
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
  - object: /home/ec2-user/cirf-be
    owner: ec2-user
    group: ec2-user
    mode: 644
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/stop-app.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/install-deps.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start-app.sh
      timeout: 300
      runas: ec2-user
